### ISSUE TITLE
Register Idea - Set Version

### ISSUE THREAD

**Issue by vilaralmeida** [filhocf/ideax#20]
# Description
* This issue allow users to set the idea version at the creation moment. As a suggestion, the system shows the number "1.0" with css placeholder component:

`<input type="text" name="ideaversion" placeholder="1.0">` 

# Project Planning Info
* This Issue is related to WBS's item 1.1.1.1

**Comment by vilaralmeida** [comment]
@filhocf @kelvin-neves @rwfalcao  reading the manage ideas section of Clarity PPM Idea Management process, we can see some attributes of an idea that we are not using in the ideax. As a suggestion, we can read the following url and see what we can incorporate at ideax

https://docops.ca.com/ca-ppm/14-2/en/using/demand-management/manage-ideas

**Comment by arthurguima** [comment]
Should the user define the version number? I think that it would be better if every time the user edits the idea it automatically changes the version number.  

Besides that i have compiled the Clarity´s attributtes.

- Subject
- Idea ID
- Idea Priority - Choices are: Low (default), Medium, and High.
- Description
- Manager
- Originating Requestor
- General Notes
- Impact on Existing Initiatives
- Risks
- Dependencies

**Comment by vilaralmeida** [comment]
@arthurguima  This is a way to let the user control the idea version number according to the evolution of any documentation attached to the idea. This is the same approach used by ckan. I think that if automatically increment the version number can make some confusion with attached files versions

**Comment by filhocf** [comment]
Moved to https://github.com/dataprev/ideax/issues/11
