### ISSUE TITLE
Register Idea - Show License

### ISSUE THREAD

**Issue by vilaralmeida** [filhocf/ideax#23]
# Description
* During the idea registration, the system shows information about the license. The information can be showed as a tip in the end of the insertion page.

`<span class="info-block info-inline">
<i class="icon-info-sign"></i>
  | A Licença Creative Commons está associada a essa ideia. Caso queira saber mais informações sobre licenças, acesse o endereço <a href="http://opendefinition.org/licenses/">opendefinition.org</a>
  | </span>`

# Project Planning Info
* This Issue is related to WBS's item 1.1.1.1

**Comment by filhocf** [comment]
This issue is a different way for issue #17. One time that the user enter into system, he need to accept the "term of service", where is explained the license and others rules about the copyright and assignment of rights about that submitted idea.

In this way, this issue is duplicated  of #17.
