### ISSUE TITLE
Idea Visualization - Idea Update Restrictions

### ISSUE THREAD

**Issue by vilaralmeida** [filhocf/ideax#29]
# Description
* This issue aims to implement a business rule to restrict the idea update to a limited set of phases of idea lifecycle.

   * As a suggestion, after approval phase the idea should not be updated

# Project Planning Info
* This Issue is related to WBS's item 1.1.2.5

**Comment by kelvin-neves** [comment]
was defined update idea just in discussion phase

**Comment by filhocf** [comment]
Moved to https://github.com/dataprev/ideax/issues/16
