### ISSUE TITLE
Idea Analysis - Visualize Technical Details

### ISSUE THREAD

**Issue by vilaralmeida** [filhocf/ideax#30]
# Description
* This issue aims to implement a page to show the following information about the idea:

   * All the informations contained in the "visualize idea" page
   * All the dimensions related to the idea
   * The points assigned to each dimension

# Project Planning Info
* This Issue is related to WBS's item 1.1.3.1

**Comment by filhocf** [comment]
Moved to https://github.com/dataprev/ideax/issues/17
