### ISSUE TITLE
Idea Analysis - Select Idea

### ISSUE THREAD

**Issue by vilaralmeida** [filhocf/ideax#31]
# Description
* This issue aims to implement a feature to allow the idea manager team to "promote" a idea to the idea planning phase (Where is made the decision to start the business plan). After the promotion to this specific phase, we can send a message to the Author to explain to him what we expect from the pitching and help him to make his pitching.

# Project Planning Info
* This Issue is related to WBS's item 1.1.3.4

**Comment by filhocf** [comment]
Moved to https://github.com/dataprev/ideax/issues/18
