### ISSUE TITLE
Idea lifecycle - Changing Idea Phase 

### ISSUE THREAD

**Issue by vilaralmeida** [filhocf/ideax#32]
# Description
* Create a set of access profiles and test what profiles has the access to promote the idea to an specific phase of its lifecycle.

   * Select Idea
   * Approve Idea (after first pitch)
   * Approve Qualified Idea (after second pitch)
   * Promove Idea to Development phase

# Project Planning Info
* This Issue is related to WBS's item 1.1.4

**Comment by kelvin-neves** [comment]
the django groups will be use to control this access.

**Comment by filhocf** [comment]
Moved to https://github.com/dataprev/ideax/issues/19
