### ISSUE TITLE
Idea Management - Report Page

### ISSUE THREAD

**Issue by vilaralmeida** [filhocf/ideax#33]
# Description
* Implement a page with filters to select subsets of ideas based on the following criteria:

   * Period of submission (Begin Date - End Date)
   * Idea Phase
   * Author's organizational unit
   * Period of last Update  (Begin Date - End Date)
   * Most upvoted 
   * Most downvoted 

# Project Planning Info
* This Issue is related to WBS's item 1.3.1

**Comment by filhocf** [comment]
Moved to https://github.com/dataprev/ideax/issues/20
