### ISSUE TITLE
Idea Management - Create Dimension

### ISSUE THREAD

**Issue by vilaralmeida** [filhocf/ideax#35]
# Description
* Create dimension supporting the following criteria:

   * Oportunnity (Oportunidade)
   * Visibility (Visibilidade)
   * Service Complexity (Complexidade do Serviço)
   * Profitability (Rentabilidade)
   * Company Strategy (Estratégia da Empresa)
   * Executive Strategy (Estratégia Executivo)
   * Customer Loyalty (Fidelização)

# Project Planning Info
* This Issue is related to WBS's item 1.1.5

**Comment by filhocf** [comment]
Moved to https://github.com/dataprev/ideax/issues/22
