### ISSUE TITLE
Adjust the use of bot in the help according .env file

### ISSUE THREAD

**Issue by filhocf** [filhocf/ideax#50]
Adjust the use of bot into help if it was set in .env file, e.g., if add a variable like DIALOGFLOW_ID in .env file, appears the chatbot into app, otherwise it don't appears in the interface.

![image](https://user-images.githubusercontent.com/952596/40016140-b87a9150-578b-11e8-974b-46a2fb068770.png)

![image](https://user-images.githubusercontent.com/952596/40016161-c82af8f6-578b-11e8-8bc8-6688c9173f67.png)

**Comment by kelvin-neves** [comment]
add feature to get DIALOGFLOW_ID from env file
